[jobs.cli-vault-korean]
command = [
    "cargo",
    "run",
    "convert",
    "/mnt/c/Users/Lev/Obsidian/Vault/Languages/한국어",
]
need_stdout = true
allow_failures = true
allow_warnings = true

[jobs.markdown-demo]
command = ["cargo", "run", "markdown", "demo"]
need_stdout = true
allow_failures = true
allow_warnings = true


[jobs.sync-demo]
command = ["cargo", "run", "sync", "demo", "Korean::Obsidian"]
need_stdout = true
allow_failures = true
allow_warnings = true
