[env]
RUST_BACKTRACE = "1"

[jobs.cli-vault-korean]
command = [
    "cargo",
    "run",
    "convert",
    "/mnt/c/Users/Lev/Obsidian/Vault/Languages/한국어",
]
need_stdout = true
allow_failures = true
allow_warnings = true

[jobs.markdown-demo]
command = ["cargo", "run", "markdown", "demo"]
need_stdout = true
allow_failures = true
allow_warnings = true


[jobs.sync-demo]
command = [
    "cargo",
    "run",
    "--features",
    "ureq_blocking",
    "--",
    "-v",
    # "-v",
    "sync",
    # "--delete-all",
    "--deck",
    "Korean::md2anki",
    "--model",
    "Basic",
    "--css",
    "cards_style.css",
    "test",
]
need_stdout = true
allow_failures = true
allow_warnings = true

[jobs.cli]
command = ["cargo", "run", "--", "sync", "help"]
need_stdout = true
allow_failures = true
allow_warnings = true
